// mobx-app/src/ValueSetDisplay.jsx
import React from 'react'
import PropTypes from 'prop-types'
import { inject, observer } from 'mobx-react'

/** show the display of a value set code */
//@inject('ValueSetStore')
//@observer
const ValueSetDisplay = inject('ValueSetStore')(observer(class ValueSetDisplay extends React.Component {

    static propTypes = {
        valueSet: PropTypes.string.isRequired,
        code: PropTypes.string.isRequired,
    }

    componentDidMount() {
        this.props.ValueSetStore.load(this.props.valueSet)
    }

    render () {

        const ValueSetStore = this.props.ValueSetStore

        if (ValueSetStore.isLoading(this.props.valueSet)) {
            return <div>Loading...</div>
        }

        if (ValueSetStore.error) {
            return <div>Error: {JSON.stringify(ValueSetStore.error)}</div>
        }

        return (
            <div>Display for <b>{this.props.code}</b> is:
                <b>{ValueSetStore.display({valueSet: this.props.valueSet, code: this.props.code}) || '-'}</b>
            </div>
        )
    }
}))


export default ValueSetDisplay

// svelte-app/src/ValueSetDisplay.svelte
<script>
// given a valueSet and code, show the display value
import { isLoading, valueSets, load, error } from './ValueSetStore.js'

// @param
export let valueSet

// @param
export let code

// ?: move test to store?
if ($valueSets[code] === undefined) {
    load(valueSet)
}
</script>

<div>Display for <b>{code}</b> is:
    {#if $isLoading}
        <b>...</b>
    {:else if $error}
        <span class="error">{$error}</span>
    {:else}
        <b>{$valueSets[code] || "–"}</b>
    {/if}
</div>

<style>
    span.error { color: #c00; font-weight: bold; }
</style>
